logging:
  level: INFO
  loggers:
    com.sebworks: DEBUG

# the key needs to match the configuration key of the renderer (ViewRenderer::getConfigurationKey)
viewRendererConfiguration:
    .ftl:
        strict_syntax: yes
#        whitespace_stripping: yes
